spring.application.name=user-auth-service
server.port=8081
spring.data.mongodb.uri=${MONGODB_URI}
service.api-key=${USER_AUTH_SERVICE_API_KEY}

# OpenAPI / Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
