spring.application.name=user-auth-service
server.port=8081
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://buddhikajanadari40_db_user:G1AUfzbuddhikajanadari40_db_userHGphj7U0ER@cluster0.kjkt3bu.mongodb.net/washflow_users?retryWrites=true&w=majority&appName=Cluster0}
service.api-key=${USER_AUTH_SERVICE_API_KEY:washflow-user-auth-dev-key-2026}

# OpenAPI / Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
